import { Icon } from './Icons'
import Reveal from './Reveal'

const projects = [
  { title: 'WayFinder', type: 'Campus navigation system', description: 'A full-stack campus navigation experience with interactive mapping, location search, REST APIs, and route planning.', stack: ['React.js', 'FastAPI', 'SQLite', 'OpenStreetMap', 'Tailwind CSS'], source: 'https://github.com/manjurahmad-tamboli/WayFinder', action: 'View source', featured: true, preview: 'map' },
  { title: 'Smart Face Attendance', type: 'Computer vision project', description: 'An attendance system that recognizes registered faces through a camera and records student details with timestamps.', stack: ['Python', 'OpenCV', 'NumPy', 'Pandas', 'CSV'], preview: 'face' },
  { title: 'Healthcare Data Analysis', type: 'Analytics dashboard', description: 'A healthcare analytics project for examining patient records, disease patterns, risk factors, and visual insights.', stack: ['Python', 'Pandas', 'NumPy', 'Matplotlib'], preview: 'data' },
]

function Preview({ kind }) { return <div className={`project-preview preview-${kind}`} aria-hidden="true">{kind === 'map' && <><span className="map-road one" /><span className="map-road two" /><span className="map-road three" /><i className="pin pin-one" /><i className="pin pin-two" /><i className="pin pin-three" /></>}{kind === 'face' && <><div className="face-frame"><span /><span /><span /><span /><div className="face-orbit" /></div><div className="scan-line" /></>}{kind === 'data' && <><div className="chart-bars">{[34, 63, 45, 84, 57, 92].map((height, i) => <span key={i} style={{ height: `${height}%` }} />)}</div><div className="chart-line"><i /><i /><i /><i /></div></>}</div> }

export default function Projects() { return <section id="projects" className="portfolio-shell py-24 sm:py-28" aria-labelledby="projects-heading"><Reveal><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Selected work</p><h2 id="projects-heading" className="section-title">Projects built around real use cases.</h2></div><a href="https://github.com/manjurahmad-tamboli" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-sm font-medium text-teal-200 hover:text-teal-100">View GitHub profile <Icon name="external" size={16} /></a></div></Reveal><div className="mt-12 grid gap-5 lg:grid-cols-3">{projects.map((project, index) => <Reveal key={project.title} className={index ? `reveal-delay-${index}` : ''}><article className="glass group flex h-full flex-col overflow-hidden rounded-2xl transition duration-300 hover:-translate-y-1.5 hover:border-teal-200/30 hover:shadow-[0_22px_48px_rgba(0,0,0,.24)]"><Preview kind={project.preview} /><div className="flex flex-1 flex-col p-6"><p className="text-xs font-medium uppercase tracking-[.16em] text-teal-200">{project.type}</p><h3 className="mt-3 text-xl font-semibold tracking-tight text-white">{project.title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{project.description}</p><div className="mt-5 flex flex-wrap gap-1.5">{project.stack.map((item) => <span key={item} className="tag !px-2 !py-0.5 !text-[11px]">{item}</span>)}</div><div className="mt-7 flex flex-wrap items-center gap-x-4 gap-y-2">{project.source ? <a href={project.source} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1.5 text-sm font-semibold text-white transition hover:text-teal-200">{project.action} <Icon name="arrow" size={15} /></a> : <span className="inline-flex items-center gap-1.5 text-sm text-slate-500"><Icon name="code" size={15} />Source link to add</span>}</div></div></article></Reveal>)}</div><p className="mt-5 text-xs leading-5 text-slate-500">Source links for the two offline projects can be added in <code className="text-slate-400">Projects.jsx</code> when they are published.</p></section> }
